aranya-project/aranya

release-plz.toml

We are keeping the crate versions in sync so we only need one tag. We are just putting the changelog in the github releases.

ci: configure release-plz

---

CONTRIBUTING.md
README.md

Even though we have a `CONTRIBUTING.md` in the `.github` repo, it's not easy to find.
GitHub only provides links when opening an issue or pull request as a small link at the bottom that's barely noticeable.
The document isn't available on the repo's main landing page along with the README and other docs and isn't easy to find after cloning the repo.
This will make it easier for users locate the correct document while saving us the work of maintaining duplicate copies for each repo.

contributing

---

.github/CODEOWNERS

Add `CODEOWNERS` for `gh-pages` branch.

gh-pages: codeowners

---

_config.yml

Started getting 404 errors after removing the `.nojekyll` files. Reverting that change.
Add the `.nojekyll` file to `capi/` instead of each release so it's easier to maintain.
Reverts aranya-project/aranya#61

Revert "gh-pages: exclude capi jekyll"

---

Cargo.lock
Cargo.toml
crates/aranya-client/Cargo.toml
templates/aranya-example/Cargo.lock
templates/aranya-example/Cargo.toml

Fixes a publishing issue of `aranya-client@0.5.0` using `aranya-daemon@0.5.0` as a dev-dependency. You generally don't use both path and version for dev-dependencies. In this case it should technically be possible but we hit https://github.com/crate-ci/cargo-release/issues/829

chore: release 0.5.1

---

README.md

Rust example was moved from `templates/aranya-example` to `examples/rust`.
This PR fixes a few README.md links that broke after that move.

readme fixes after rust example mv

---

Cargo.lock
Cargo.toml
crates/aranya-client-capi/Cargo.toml
crates/aranya-client-capi/output/aranya-client.h
crates/aranya-client-capi/src/api/defs.rs
examples/c/example.c

Closes #85
- Adds some utility methods to the C API for ID types
- converting an ID into a string
- converting a string into an ID
- ~~Getting the bytes of an ID as a pointer~~ The bytes of the ID structs are accessible by their field(s)

aranya-client-capi: access to bytes in ids

---

crates/aranya-client/tests/tests.rs

Our testing suite on aranya-client has been getting majorly mangled since we stubbed out AFC and started on AQC integration. This reworks the entire tests.rs to be more modular and easier to maintain in the future (i.e. less lines, less repetition, better documentation).

client: Refactor Tests

---

Cargo.lock
crates/aranya-client-capi/Cargo.toml
crates/aranya-client-capi/output/aranya-client.h
crates/aranya-client-capi/src/api/defs.rs
crates/aranya-client-capi/src/imp/client.rs
crates/aranya-client-capi/src/imp/error.rs
crates/aranya-daemon-api/src/service.rs
examples/c/example.c

Use `postcard` to serialize/deserialize key bundles.

c-api: key bundle serialization

---

crates/aranya-client/tests/tests.rs

The sync now test should test without adding sync peers so that when `sync_now` is invoked, it can prove that it caused a sync to occur.
At some point, a PR introduced adding sync peers to this test, which caused a CI flake.
Could have been one of my PRs, haven't investigated which PR introduced it yet.

ci: fix sync now test flake

---

examples/rust/Cargo.lock
examples/rust/Cargo.toml

See https://github.com/aranya-project/aranya/security/dependabot/1 for details, tokio needs to be bumped to 1.44.2. The main repo got bumped, but the example was on 1.44.1.

rust-example: Fix Tokio Vulnerability

---

Cargo.lock
Cargo.toml
crates/aranya-client-capi/output/aranya-client.h
crates/aranya-client-capi/src/api/defs.rs
crates/aranya-client-capi/src/imp/client.rs
crates/aranya-client-capi/src/imp/config.rs
crates/aranya-client/src/aqc.rs
crates/aranya-daemon-api/src/service.rs
crates/aranya-daemon/src/api.rs
crates/aranya-daemon/src/aqc.rs
examples/rust/Cargo.lock
supply-chain/audits.toml
supply-chain/config.toml
supply-chain/imports.lock

This implementation assumes that the client only supports the cipher suites listed in [RFC 8446]. This is a fine assumption for now, but we might need to change it in the future if we allow users to customize the TLS implementation.
To change this, the caller could supply the list of supported cipher suites. Or the daemon could send the `BidiSecret`/`UniSecret` to the client, but that's trickier since `BidiSecret` and `UniSecret` are currently wrappers around the HPKE context, which can't reasonably be `Serialize`/`Deserialize`.
Fixes #259
[RFC 8446]: https://datatracker.ietf.org/doc/html/rfc8446#appendix-B.4

aqc: pair PSKs with cipher suites

---

Cargo.lock
Cargo.toml
examples/rust/Cargo.lock

Bump aranya crate versions for release 0.6.0.
This release includes the new AQC feature.
The following PRs should be merged before this one:

release: 0.6.0

---

examples/rust/README.md

Rust example README is out-of-date after the AQC release.
This PR gets the README up-to-date and makes it less likely to become out of date in the future by removing implementation specific references/links from the README.

aqc: update rust example readme

---

crates/aranya-client/src/aqc/net.rs

Read to the end of the stream and ignore close error when acking.
Kind of silly to me what make this fail AFAICT.
- Peer is reading all data until stream is finished
- We close the stream, which marks it as finished and "flushes" to wait for ack of all data
- The peer finishes reading all the data and closes the stream
- Our flushing fails because the stream is closed, even though the peer couldn't have closed it until after we called close
- This really feels like bad behavior to me.

Fix ctrl recv error causing flake

---

crates/aranya-client-capi/docs/static/mainpage.md
crates/aranya-client-capi/output/aranya-client.h
crates/aranya-client-capi/src/api/defs.rs

The existing Doxygen docs are not detailed enough for a reader to easily figure out how to initialize the various config objects in the Aranya client's C API.
These docs describe how to use the builder objects to initialize config objects.

capi: better cfg init docs

---

examples/c/example.c

Replace `malloc()` with `calloc()` in the C example.
This task was mostly completed already but I found one remaining `malloc()`.

c example: replace malloc with calloc

---

Cargo.lock
Cargo.toml
crates/aranya-client-capi/src/imp/aqc.rs
crates/aranya-client-capi/src/imp/client.rs
crates/aranya-client-capi/src/imp/config/team.rs
crates/aranya-client-capi/src/imp/config/team/quic_sync.rs
crates/aranya-client-capi/src/imp/error.rs
crates/aranya-client/src/aqc/net.rs
crates/aranya-client/src/client.rs
crates/aranya-client/src/config.rs
crates/aranya-client/src/config/team.rs
crates/aranya-client/src/config/team/quic_sync.rs
crates/aranya-client/src/error.rs
crates/aranya-daemon/Cargo.toml
crates/aranya-daemon/src/actions.rs
crates/aranya-daemon/src/api.rs
crates/aranya-daemon/src/aqc.rs
crates/aranya-daemon/src/config/toggle.rs
crates/aranya-daemon/src/daemon.rs
crates/aranya-daemon/src/sync/task.rs
crates/aranya-daemon/src/sync/task/quic.rs
crates/aranya-util/src/task.rs

Eagerly implement `Debug` trait in the client's public Rust API:
https://rust-lang.github.io/api-guidelines/checklist.html
This PR adds whatever `Debug` traits can be easily added.
There are some cases where implementing traits would be more involved because the underlying types in `aranya-core` or a 3rd party lib would also need to implement those traits. This PR does not attempt to handle those cases.

client: eagerly implement Debug trait in public API

---

crates/aranya-client-capi/docs/static/mainpage.md

New types were added for `CreateTeam` and `AddTeam`. Fix the links to these types on the Doxygen landing page.

doxygen: fix type links

---

crates/aranya-client/src/client.rs
crates/aranya-util/src/task.rs
rustfmt.toml

Add a `rustdoc` example showing how the Aranya client can connect to the Aranya daemon.

rustdoc: connect example

---

crates/aranya-daemon/src/sync/task/quic.rs
crates/aranya-daemon/src/sync/task/quic/connections.rs

I got drawn into doing some refactoring. I moved the server select arms into methods, and made the shared connection map not expose the lock as part of the API.

Shared connection refactor

---

crates/aranya-client-capi/src/api/defs.rs

This is one location where excessive errors are logged by aranya. This line would log even during non-fatal errors like WouldBlock, causing logs to fill up quickly. 
Another solution could be to not log on WouldBlock and other non-fatal errors.

logging: remove error! from From impl

---

Cargo.lock
deny.toml
supply-chain/audits.toml
supply-chain/config.toml
supply-chain/imports.lock

https://rustsec.org/advisories/RUSTSEC-2025-0055

chore: update to `tracing-subscriber@0.3.20`

---

examples/c/example.c

This should fix the crashes that occurred when we had other errors.
We were "cleaning up" uninitialized objects when an error occurred. We now basically just exit on an error. There isn't really a need to do the cleanup here on errors. It's probably worth having in a more realistic example but this example is basically just a test script.

c-example: fix crash on errors in example
